[package]
name = "bencode-afl"
version = "0.1.0"
authors = ["Stacey Ell <stacey.ell@gmail.com>"]

[dependencies.bencode]
path = ".."
features = ["afl"]

[dependencies]
afl = "0.1.0"
afl-plugin = "0.1.0"
